--Write your PL/SQL query statement */
SELECT PRICES.PRODUCT_ID, NVL(ROUND(SUM(PRICES.price* UNITSSOLD.units)/ SUM(UNITSSOLD.units), 2),0) as average_price FROM PRICES
LEFT JOIN UNITSSOLD ON PRICES.PRODUCT_ID = UNITSSOLD.PRODUCT_ID
AND UNITSSOLD.purchase_date BETWEEN  PRICES.start_date AND PRICES.end_date
GROUP BY PRICES.product_ID;